### ISSUE TITLE
segments do not work with 1.4 update

### ISSUE THREAD

**Issue by dhango** [debrouwere/python-omniture#6]
Hi,

I've been using your package to query from Omniture using segment filters and it worked fine. However, with the new 1.4 segment identifiers (e.g. no "dsc" prefix) and using the same code that had worked before, I was no longer able to query from Omniture.  I re-installed and updated your package and still got the following error.

Traceback (most recent call last):
  File "/home/derrick/bin/test/pycharm//bing_test.py", line 51, in <module>
    '53a9e31fe4b09398b55895ab', qc_web[0], rent_web[0])
  File "/home/derrick/bin/test/pycharm/call_Omniture.py", line 16, in call_Omniture
    .filter(segment=segID) \
  File "/usr/local/lib/python2.7/dist-packages/omniture/query.py", line 16, in wrapped_method
    method(obj, _vargs, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/omniture/query.py", line 122, in filter
    self.raw['segment_id'] = self._normalize_value(segment, 'segments').id
  File "/usr/local/lib/python2.7/dist-packages/omniture/query.py", line 35, in _normalize_value
    return getattr(self.suite, category)[value]
  File "/usr/local/lib/python2.7/dist-packages/omniture/utils.py", line 39, in __getitem__
    key=key, name=self.name))
KeyError: 'Cannot find 53a9e31fe4b09398b55895ab among the available segments'

I ran the new 1.4 segment filters with Omniture wrappers in R and php and it worked fine. Wondering if you have any idea what is going on here? Any help would be appreciated.

Thanks!

**Comment by dhango** [comment]
Used dancingcactus' version. Querying works fine now. Thanks.
